spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    ## kebaba case
    # driver-class-name
    ## snake case
#    driver-class-name
mybatis:
  config-location: classpath:db/mybatis/config.xml